site_name: Maia's Documentation
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tabs
extra_css:
  - extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/facebook
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/slack
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/gitlab
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/linkedin
      link: https://www.maiaroos.com

plugins:
  - search

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences  

nav:
  - Home: 
    - Welcome: index.md
    - How To:
      - how-to/how-to-guides.md
    - Blog:
      - blog/blog.md

site_dir: public/